version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: meubanco
      MYSQL_USER: laura
      MYSQL_PASSWORD: senha123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: minha_app
    environment:
      DB_HOST: db
      DB_USER: laura
      DB_PASSWORD: senha123
      DB_NAME: meubanco
    depends_on:
      - db
    networks:
      - minha_rede
    ports:
      - "5000:5000"

volumes:
  mysql_data:

networks:
  minha_rede:
    driver: bridge
